import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
const geistSans = Montserrat({
  variable: "--font-monsterrat",
  subsets: ["latin"],
});

const geistMono = Montserrat({
  variable: "--font-monsterrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
